const detdomMembers = {
  members: [
    {
      name: "Антон Кудрявцев",
      age: 15,
      height: 180,
      role: "Админ",
      gender: "Муж.",
      birthyear: "24 янв",
      description: `Выпустил крутой альбом Дурные Дети!`,
      img: "https://sun9-east.userapi.com/sun9-20/s/v1/if2/tifxcvR0f9pHry8VXEAGqgGVvxvF-KQ6xVdSqHQZSg55jZeoSLvX1fa4sj-JpAKnHhlhXKVQiLrSXAQ2XikcdoOz.jpg?size=675x449&quality=95&type=album",
      id: 0,
    },

    {
      name: "Тимофей Карпов",
      age: 15,
      height: 178,
      role: "Админ",
      gender: "Муж.",
      birthyear: "16 мая",
      description: "Крутой админ детдома",
      img: "https://sun9-east.userapi.com/sun9-31/s/v1/if2/qFLQHFGS_FVaxT8cxuOTKUr9U44QDQBsVV7-OWRpEvp5-4Ktyt986jRz9jmp5qpnNcKcDYsPW-q3IQ9pj-PeHfX6.jpg?size=675x449&quality=95&type=album",
      id: 1,
    },

    {
      name: "Сглыпа",
      age: 3,
      height: 105,
      role: "Админ",
      gender: "Интерсекс",
      birthyear: "N/A",
      description: "Крутая горошина, с которой можно посмеяться",
      img: "https://sun2.43222.userapi.com/s/v1/if1/9H4DMTIWUrueWKTowWrlGHJ86RP8xdM4R8xOTQ73XWot8DxMA-X4aL6M14vavndPaqw5KVjV.jpg?size=1280x720&quality=96&type=album",
      id: 2,
    },

    {
      name: "Артем Шибаев",
      age: 16,
      height: 180,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "6 дек",
      description: "Геральт из Ривии",
      img: "https://sun9-east.userapi.com/sun9-25/s/v1/if2/yuIquRtJY-ywVrjFh3RISaJwMgdvNIFXFv3KE6cHpfcjF10yMb7VHxCaLl3cSNCW8_omy_k51lDSAeXUksMRScmY.jpg?size=1280x684&quality=95&type=album",
      id: 3,
    },

    {
      name: "Крипусси",
      age: 15,
      height: 181,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "31 дек",
      description: "Надел на себя череп и всех рубил на мясо",
      img: "https://sun9-west.userapi.com/sun9-38/s/v1/if2/FQu6ACyi8YSTUCYMj8FgO3PtjeQqc8eXumyyI0HW2lOefyy7SlZrkhmcljqKMF06gIcE16m-ravFuqnkigx57mkH.jpg?size=1280x1164&quality=95&type=album",
      id: 4,
    },

    {
      name: "Даниил Чайковский",
      age: 16,
      height: 182,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "5 авг",
      description: "Кидает смешные картинки и видел психо в живую",
      img: "https://sun9-east.userapi.com/sun9-25/s/v1/if2/PgZ9FFzEwK-qbVAlNsiNo2u6CwdE2ldKvLXfviUN86NQitSUcg05FUz5VtDpKsmYmXmj0xE2NoTZjLp9gayOuwTU.jpg?size=952x1080&quality=95&type=album",
      id: 5,
    },

    {
      name: "Гердачка",
      age: 15,
      height: 175,
      role: "Участ.",
      gender: "Жен.",
      birthyear: "29 мая",
      description: "Играет в геншин импак 25/8",
      img: "https://sun2.43222.userapi.com/s/v1/if2/pTQAaKCDE_4_ZsPPdVoqGOlbhpcDbUsfg0vMUAbdLxM6ShU3Sy_dVQ46fg64dSKVQzVko8OU8zO75RyAA4PTRsyW.jpg?size=844x1116&quality=95&type=album",
      id: 6,
    },

    {
      name: "Мансур Фруктов",
      age: 16,
      height: 177,
      role: "Участ.",
      gender: "Фрукт",
      birthyear: "13 янв",
      description: "Пишет всякую херню и уходит",
      img: "https://sun9-west.userapi.com/sun9-61/s/v1/ig2/4zGnMdlC9pEC9v_Z_8yot6mTjY3rQvN1J8Y3Gk2cAQvcf3LgZbMwdFtF8GKvjaDzlHGOL3aNSvd4g_5B8bsNasAL.jpg?size=600x400&quality=95&type=album",
      id: 7,
    },

    {
      name: "Никита Мартюченко",
      age: 18,
      height: 181,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "22 сен",
      description: "Находится в Армии",
      img: "https://sun9-east.userapi.com/sun9-26/s/v1/if2/MZ4w7uvCLrWxUMSkIqZQzkQkacqC6sJMNqc5l6OhJSfmMjd_yABNFnlrar8lU55YDHwNPV98AA4Nq0FhKxGYzVvj.jpg?size=878x803&quality=95&type=album",
      id: 8,
    },

    {
      name: "Свят Светличный",
      age: 15,
      height: 180,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "24 мар",
      description: "Заходит в войс сказать, что ложиться спать",
      img: "https://sun2.43222.userapi.com/s/v1/ig2/4J3xKd7xediGQ1B2usAkWwcwgU51b0opR2eWvbUIAdXtKFsUoI3pVYy86lg6MC3ek3H2KZrb29S0idTXqCblBP-T.jpg?size=808x1080&quality=95&type=album",
      id: 9,
    },

    {
      name: "Даниил Андреев",
      age: 15,
      height: 179,
      role: "Участ.",
      gender: "Кодер",
      birthyear: "10 сент",
      description: "Играет в Visual Studio Code",
      img: "https://sun9-east.userapi.com/sun9-20/s/v1/if2/5ak6G5-YHkyu-ac04d65qfvv4mMpXGvbuijGOdyfJHmX2ZwTFYX7pHucVRC_PIbGmk8n7X_J0iJUpFZ6-RHrOIBI.jpg?size=671x400&quality=95&type=album",
      id: 10,
    },

    {
      name: "Gerbert Turan",
      age: 19,
      height: 178,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "1 апр",
      description: "Пишет конструктив и подкатывает к 8-ми классницам",
      img: "https://sun9-north.userapi.com/sun9-82/s/v1/if2/3qYEIf61Bmtm8CglokoP5KGiuqdgKTjMWWrw_C70RcfWYCc9k7guPdmLuJlnoAFWs1U_kiPfDMScv9JA3MfMAh9c.jpg?size=960x960&quality=95&type=album",
      id: 11,
    },

    {
      name: "Илья Тоугорин",
      age: 16,
      height: 178,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "1 окт",
      description: "Постоянно кайфует в FL Studio",
      img: "https://sun2.43222.userapi.com/s/v1/ig2/ABJOrI0a-IzRgo9EMq-4yezsj3yZZ8NCZu76hmLMdoPGmxPjTKEDlERDv52RSRVuvz2371HfA5RSDE58Tx4viT0Q.jpg?size=200x200&quality=96&crop=468,60,362,362&ava=1",
      id: 12,
    },

    {
      name: "Валера Серебряков",
      age: 15,
      height: 179,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "22 нояб",
      description: "Смешно озвучивает кошко-девочек",
      img: "https://sun9-east.userapi.com/sun9-35/s/v1/if2/M4q574ZzXy30wiY_8vHQ_m1IyH6BxdkBlyqQsGsCll7gn58M4gF0efXdtz_RLYWYB4jc98WGcWobbtCW21GfDrHO.jpg?size=884x1080&quality=95&type=album",
      id: 13,
    },

    {
      name: "Вадим Дмитриевич",
      age: 19,
      height: 180,
      role: "Участ.",
      gender: "Муж.",
      birthyear: "N/A",
      description: "Получил рутэда в лкоме",
      img: "https://sun9-west.userapi.com/sun9-61/s/v1/if2/iQ-lWmAtptBd9DBUvPCo8KKQl5sNJ-C2V36ynNANZ-xE13bi305BScyGgWZuHiL_TQKZjYNK8NuecZH1QvnUYpeV.jpg?size=924x1080&quality=96&type=album",
      id: 14,
    },

    {
      name: "Wgmlgz",
      age: 17,
      height: 181,
      role: "Участ.",
      gender: "Кодер",
      birthyear: "21 мая",
      description: "Никогда не пишет в детдоме.",
      img: "https://sun1.43222.userapi.com/s/v1/ig2/hsst8lql-ps1xiMZ6AatKGXN3ZpVOfy6dyIZtoE6y-9nK2nxIIBYBYfJNkJ6xpjXx5eq2_ITTRNxxWdBp1RANab9.jpg?size=200x200&quality=95&crop=234,0,653,653&ava=1",
      id: 15,
    },

    {
      name: "Никита Соловьев",
      age: 16,
      height: 181,
      role: "Участ.",
      gender: "крутой",
      birthyear: "21 апр",
      description: "крутой бравлстарсер",
      img: "https://sun9-east.userapi.com/sun9-58/s/v1/ig2/8hIK3XIvQoiw5v1KUwGlsC97aDYHzBaudNI5jgrdpcgytf6ekNcGucL5Vwt1pRpj57MHzu2umMXj-UoRN9GuIhbf.jpg?size=810x1080&quality=95&type=album",
      id: 16,
    },

    {
      name: "Александр Орлов",
      age: 15,
      height: 178,
      role: "Участ.",
      gender: "Бродяга",
      birthyear: "2 окт",
      description: "Купил Бродягу за рубль и забыл пароль на сервере",
      img: "https://sun9-west.userapi.com/sun9-37/s/v1/ig2/y2gON-Dx50lIs4TI1fTC_nZGFRaqkk9-NL1eNGs0PmwpyVt6YCHtFkFschdOy_8Lc1nJIlyhVpgEGmFQtLZhh3Il.jpg?size=1280x861&quality=95&type=album",
      id: 17,
    },

    {
      name: "Серожа",
      age: 16,
      height: 179,
      role: "Участ.",
      gender: "Дотер",
      birthyear: "1 сен",
      description: "Играл в доту против zxcAlenka",
      img: "https://avatars.mds.yandex.net/get-images-cbir/1356362/icrHwCs7jKJ2mLyRVl0xnQ4978/ocr",
      id: 18,
    },
  ],
};

// Экспортируем файл, что бы мы могли получить его данные в другом файле
export { detdomMembers };
